spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      value-deserializer: com.kevvlvl.financeapi.deserializer.StockDeserializer
      group-id: stock_gid
  datasource:
    username: postgres
    password: stocks1234
    url: jdbc:postgresql://localhost:5432/postgres

logging:
  level:
    ROOT:
      info

server:
  port: 8091
